# author: adrian jones

common_adjectives = {
    "good", "new", "first", "last", "long", "great", "little", "own", "other", "old", "right", "big", "high",
    "different", "small", "large", "next", "early", "young", "important", "few", "public", "bad", "same", "able",
    "full", "far", "low", "late", "hard", "major", "better", "economic", "strong", "possible", "whole", "free",
    "military", "true", "federal", "international", "easy", "clear", "recent", "certain", "personal", "open", "red",
    "difficult", "available", "likely", "short", "single", "medical", "current", "wrong", "private", "past", "foreign",
    "fine", "common", "poor", "natural", "significant", "similar", "hot", "dead", "central", "happy", "serious",
    "ready", "simple", "left", "physical", "general", "environmental", "financial", "blue", "democratic", "dark",
    "various", "entire", "close", "legal", "religious", "cold", "final", "main", "green", "nice", "huge", "popular",
    "traditional", "cultural", "wide", "particular", "top", "real", "best", "left", "sure", "special", "clear",
    "local", "beautiful", "successful", "fair", "green", "heavy", "fast", "wonderful", "tiny", "additional", "high",
    "sweet", "expensive", "strange", "thin", "specific", "dark", "yellow", "neat", "practical", "dry", "fresh",
    "pink", "wild", "commercial", "full", "low", "primary", "worth", "necessary", "positive", "present", "close",
    "creative", "green", "late", "fit", "glad", "obvious", "simple", "excellent", "constant", "primary", "tired",
    "detailed", "ready", "central", "satisfied", "proud", "vast", "bright", "smooth", "hot", "warm", "useful",
    "afraid", "sharp", "healthy", "curious", "realistic", "pleased", "comfortable", "true", "valuable", "pleased",
    "tight", "cold", "attractive", "wealthy", "warm", "quiet", "concerned", "clean", "nice", "common", "fresh",
    "smart", "interesting", "poor", "fantastic", "grown", "complex", "crazy", "adorable", "cool", "exotic", "fabulous",
    "gorgeous", "grumpy", "handsome", "innocent", "juicy", "lazy", "magnificent", "mysterious", "quirky", "rare",
    "silly", "sparkling", "spicy", "tender", "vibrant", "zesty", "zippy"
}

silly_adjectives = {
    "absurd", "antsy", "batty", "befuddled", "blundering", "bumbling", "bumpkin", "cackling", "clownish", "clumsy",
    "comical", "cracked", "crazed", "crazy", "cuckoo", "daffy", "dizzy", "dopey", "dorky", "dotty", "dumb", "dunderheaded",
    "eccentric", "erratic", "farcical", "flaky", "flippant", "fluffy", "foolish", "frivolous", "fuddled", "fumbling",
    "funny", "fuzzy", "gaga", "geeky", "giddy", "goofy", "gormless", "harebrained", "hilarious", "humorous", "hysterical",
    "idiotic", "imbecilic", "inane", "insane", "jittery", "jolly", "jumpy", "kooky", "laughable", "loony", "ludicrous",
    "lunatic", "madcap", "mirthful", "moronic", "nervous", "nonsensical", "nutty", "odd", "peculiar", "potty", "preposterous",
    "quaint", "quirky", "ridiculous", "risible", "scatterbrained", "screwball", "shaky", "silly", "skittish", "slaphappy",
    "slightly", "smiling", "snickering", "squirrely", "stupid", "unhinged", "unserious", "unsteady", "wacky", "whimsical",
    "witty", "wobbly", "zany", "zippy", "klutzy", "whacky", "nutso", "noodle-headed", "lamebrained", "topsy-turvy",
    "ditsy", "loopy", "droll", "risible", "frothy", "dippy", "noodle-head", "mop", "mug", "gull", "booby", "sap", "flat",
    "gudgeon", "dullard", "mooncalf", "silly-billy", "giddy", "giddy-goat", "giddy-head", "giddy-pate", "saphead",
    "cabbagehead", "muff", "featherhead", "absurd", "antsy", "batty", "befuddled", "blundering", "bumbling", "bumpkin",
    "cackling", "clownish", "clumsy", "comical", "cracked", "crazed", "crazy", "cuckoo", "daffy", "dizzy", "dopey",
    "dorky", "dotty", "dumb", "dunderheaded", "eccentric", "erratic", "farcical", "flaky", "flippant", "fluffy",
    "foolish", "frivolous", "fuddled", "fumbling", "funny", "fuzzy", "gaga", "geeky", "giddy", "goofy", "gormless",
    "harebrained", "hilarious", "humorous", "hysterical", "idiotic", "imbecilic", "inane", "insane", "jittery", "jolly",
    "jumpy", "kooky", "laughable", "loony", "ludicrous", "lunatic", "madcap", "mirthful", "moronic", "nervous", "nonsensical",
    "nutty", "odd", "peculiar", "potty", "preposterous", "quaint", "quirky", "ridiculous", "risible", "scatterbrained",
    "screwball", "shaky", "silly", "skittish", "slaphappy", "slightly", "smiling", "snickering", "squirrely", "stupid",
    "unhinged", "unserious", "unsteady", "wacky", "whimsical", "witty", "wobbly", "zany", "zippy", "klutzy", "whacky",
    "nutso", "noodle-headed", "lamebrained", "topsy-turvy", "ditsy", "loopy", "droll", "risible", "frothy", "dippy",
    "noodle-head", "mop", "mug", "gull", "booby", "sap", "flat", "gudgeon", "dullard", "mooncalf", "silly-billy", "giddy",
    "giddy-goat", "giddy-head", "giddy-pate", "saphead", "cabbagehead", "muff", "featherhead", "absurd", "antsy", "batty",
    "befuddled", "blundering", "bumbling", "bumpkin", "cackling", "clownish", "clumsy", "comical", "cracked", "crazed",
    "crazy", "cuckoo", "daffy", "dizzy", "dopey", "dorky", "dotty", "dumb", "dunderheaded", "eccentric", "erratic",
    "farcical", "flaky", "flippant", "fluffy", "foolish", "frivolous", "fuddled", "fumbling", "funny", "fuzzy", "gaga",
    "geeky", "giddy", "goofy", "gormless", "harebrained", "hilarious", "humorous", "hysterical", "idiotic", "imbecilic",
    "inane", "insane", "jittery", "jolly", "jumpy", "kooky", "laughable", "loony", "ludicrous", "lunatic", "madcap",
    "mirthful", "moronic", "nervous", "nonsensical", "nutty", "odd", "peculiar", "potty", "preposterous", "quaint", "quirky",
    "ridiculous", "risible", "scatterbrained", "screwball", "shaky", "silly", "skittish", "slaphappy", "slightly", "smiling",
    "snickering", "squirrely", "stupid", "unhinged", "unserious", "unsteady", "wacky", "whimsical", "witty", "wobbly", "zany",
    "zippy", "klutzy", "whacky", "nutso", "noodle-headed", "lamebrained", "topsy-turvy", "ditsy", "loopy", "droll", "risible",
    "frothy", "dippy", "noodle-head", "mop", "mug", "gull", "booby", "sap", "flat", "gudgeon", "dullard", "mooncalf",
    "silly-billy", "giddy", "giddy-goat", "giddy-head", "giddy-pate", "saphead", "cabbagehead", "muff", "featherhead",
    "absurd", "antsy", "batty", "befuddled", "blundering", "bumbling", "bumpkin", "cackling", "clownish", "clumsy",
    "comical", "cracked", "crazed", "crazy", "cuckoo", "daffy", "dizzy", "dopey", "dorky", "dotty", "dumb", "dunderheaded",
    "eccentric", "erratic", "farcical", "flaky", "flippant", "fluffy", "foolish", "frivolous", "fuddled", "fumbling",
    "funny", "fuzzy", "gaga", "geeky", "giddy", "goofy", "gormless", "harebrained", "hilarious", "humorous", "hysterical",
    "idiotic", "imbecilic", "inane", "insane", "jittery", "jolly", "jumpy", "kooky", "laughable", "loony", "ludicrous",
    "lunatic", "madcap", "mirthful", "moronic", "nervous", "nonsensical", "nutty", "odd", "peculiar", "potty", "preposterous",
    "quaint", "quirky", "ridiculous", "risible", "scatterbrained", "screwball", "shaky", "silly", "skittish", "slaphappy",
    "slightly", "smiling", "snickering", "squirrely", "stupid", "unhinged", "unserious", "unsteady", "wacky", "whimsical",
    "witty", "wobbly", "zany", "zippy", "klutzy", "whacky", "nutso", "noodle-headed", "lamebrained", "topsy-turvy",
    "ditsy", "loopy", "droll", "risible", "frothy", "dippy", "noodle-head", "mop", "mug", "gull", "booby", "sap", "flat",
    "gudgeon", "dullard", "mooncalf", "silly-billy", "giddy", "giddy-goat", "giddy-head", "giddy-pate", "saphead",
    "cabbagehead", "muff", "featherhead", "absurd", "antsy", "batty", "befuddled", "blundering", "bumbling", "bumpkin",
    "cackling", "clownish", "clumsy", "comical", "cracked", "crazed", "crazy", "cuckoo", "daffy", "dizzy", "dopey",
    "dorky", "dotty", "dumb", "dunderheaded", "eccentric", "erratic", "farcical", "flaky", "flippant", "fluffy",
    "foolish", "frivolous", "fuddled", "fumbling", "funny", "fuzzy", "gaga", "geeky", "giddy", "goofy", "gormless",
    "harebrained", "hilarious", "humorous", "hysterical", "idiotic", "imbecilic", "inane", "insane", "jittery", "jolly",
    "jumpy", "kooky", "laughable", "loony", "ludicrous", "lunatic", "madcap", "mirthful", "moronic", "nervous",
    "nonsensical", "nutty", "odd", "peculiar", "potty", "preposterous", "quaint", "quirky", "ridiculous", "risible",
    "scatterbrained", "screwball", "shaky", "silly", "skittish", "slaphappy", "slightly", "smiling", "snickering",
    "squirrely", "stupid", "unhinged", "unserious", "unsteady", "wacky", "whimsical", "witty", "wobbly", "zany", "zippy",
    "klutzy", "whacky", "nutso", "noodle-headed", "lamebrained", "topsy-turvy", "ditsy", "loopy", "droll", "risible",
    "frothy", "dippy", "noodle-head", "mop", "mug", "gull", "booby", "sap", "flat", "gudgeon", "dullard", "mooncalf",
    "silly-billy", "giddy", "giddy-goat", "giddy-head", "giddy-pate", "saphead", "cabbagehead", "muff", "featherhead"
}

common_nouns = {
    "time", "year", "people", "way", "day", "man", "government", "company", "hand", "part", "place", "case", "group",
    "problem", "fact", "child", "eye", "government", "example", "family", "week", "system", "program", "question", "work",
    "number", "night", "point", "home", "water", "room", "mother", "area", "money", "story", "month", "lot", "right",
    "study", "book", "job", "word", "business", "issue", "side", "kind", "head", "house", "service", "friend", "father",
    "power", "hour", "game", "line", "end", "member", "law", "car", "city", "community", "name", "school", "country",
    "president", "team", "minute", "idea", "kid", "body", "information", "back", "parent", "face", "level", "office",
    "door", "health", "person", "art", "war", "history", "party", "result", "change", "reason", "rate", "education",
    "process", "class", "food", "union", "memory", "garden", "construction", "collection", "nature", "act", "sense",
    "knowledge", "direction", "center", "energy", "committee", "development", "management", "safety", "security",
    "organization", "language", "response", "quality", "behavior", "television", "decision", "goal", "event",
    "attention", "situation", "moment", "support", "range", "market", "interest", "care", "action", "effect", "effort",
    "field", "society", "system", "price", "method", "need", "plan", "project", "resource", "line", "product", "thought",
    "evidence", "account", "picture", "experience", "success", "value", "record", "population", "space", "film",
    "industry", "data", "research", "truth", "evening", "morning", "science", "art", "community", "night", "music",
    "difference", "investment", "future", "past", "option", "theory", "basis", "chance", "audience", "choice", "debt",
    "contract", "rule", "influence", "method", "sector", "organization", "television", "trade", "deal", "performance",
    "loss", "computer", "requirement", "letter", "association", "analysis", "relationship", "scale", "pattern", "date",
    "image", "activity", "concept", "defense", "extent", "section", "window", "opportunity", "growth", "cause",
    "material", "variation", "matter", "justice", "mile", "bed", "hair", "flight", "damage", "purchase", "radio",
    "presence", "skill", "commitment", "description", "target", "address", "breath", "doctor", "pressure", "proposal",
    "battle", "appearance", "estate", "assessment", "failure", "emergency", "status", "assistance", "session", "unit",
    "income", "significance", "criticism"
}

silly_nouns = {
    "abracadabra", "bamboozle", "bazinga", "blubber", "booger", "brouhaha", "bumfuzzle", "cahoots", "codswallop",
    "dingleberry", "doohickey", "fiddlesticks", "flibbertigibbet", "flimflam", "fuddy-duddy", "gadzooks", "gobbledygook",
    "goober", "goombah", "guffaw", "hocus-pocus", "hogwash", "hoodwink", "hullabaloo", "humbug", "kerfuffle",
    "knucklehead", "lollygag", "malarkey", "mishmash", "monkeyshines", "nincompoop", "noodle", "oogly-boogly", "piddly",
    "poppycock", "rambunctious", "rigmarole", "shenanigans", "skedaddle", "snickerdoodle", "snollygoster", "tiddlywinks",
    "wackadoo", "whatchamacallit", "wiggleworm", "wobblebottom", "wuzzup", "yahoo", "ziggurat", "zonkers", "zoinks",
    "bling-bling", "caboodle", "cockamamie", "dilly-dally", "fiddle-faddle", "fiddlesticks", "flabbergasted", "flapdoodle",
    "flibbertigibbet", "flimflam", "fuddy-duddy", "gadzooks", "gobbledygook", "goober", "goombah", "guffaw", "hocus-pocus",
    "hogwash", "hoodwink", "hullabaloo", "humbug", "kerfuffle", "knickknack", "lollygag", "malarkey", "mishmash",
    "monkeyshines", "nincompoop", "noodle", "oogly-boogly", "piddly", "poppycock", "rambunctious", "rigmarole",
    "shenanigans", "skedaddle", "snickerdoodle", "snollygoster", "tiddlywinks", "wackadoo", "whatchamacallit",
    "wiggleworm", "wobblebottom", "wuzzup", "yahoo", "ziggurat", "zonkers", "zoinks", "abracadabra", "bamboozle",
    "bazinga", "blubber", "booger", "brouhaha", "bumfuzzle", "cahoots", "codswallop", "dingleberry", "doohickey",
    "fiddlesticks", "flibbertigibbet", "flimflam", "fuddy-duddy", "gadzooks", "gobbledygook", "goober", "goombah",
    "guffaw", "hocus-pocus", "hogwash", "hoodwink", "hullabaloo", "humbug", "kerfuffle", "knucklehead", "lollygag",
    "malarkey", "mishmash", "monkeyshines", "nincompoop", "noodle", "oogly-boogly", "piddly", "poppycock",
    "rambunctious", "rigmarole", "shenanigans", "skedaddle", "snickerdoodle", "snollygoster", "tiddlywinks", "wackadoo",
    "whatchamacallit", "wiggleworm", "wobblebottom", "wuzzup", "yahoo", "ziggurat", "zonkers", "zoinks", "bling-bling",
    "brouhaha", "caboodle", "cockamamie", "dilly-dally", "fiddle-faddle", "fiddlesticks", "flabbergasted", "flapdoodle",
    "flibbertigibbet", "flimflam", "fuddy-duddy", "gadzooks", "gobbledygook", "goober", "goombah", "guffaw", "higgledy-piggledy",
    "hocus-pocus", "hogwash", "hoodwink", "hoity-toity", "hullabaloo", "humbug", "kerfuffle", "knickknack", "lollygag",
    "malarkey", "mishmash", "monkeyshines", "namby-pamby", "nincompoop", "noodle", "nincompoop", "oogly-boogly",
    "piddle", "piddly", "poppycock", "ragamuffin", "razzmatazz", "shenanigans", "skedaddle", "snickerdoodle",
    "snollygoster", "splendiferous", "tiddlywinks", "wackadoo", "whatchamacallit", "wiggleworm", "wobblebottom",
    "wuzzup", "yahoo", "ziggurat", "zonkers", "zoinks", "bamboozle", "bazinga", "blubber", "booger", "codswallop",
    "dingleberry", "doohickey", "fiddlesticks", "flibbertigibbet", "flimflam", "fuddy-duddy", "gadzooks", "gobbledygook",
    "goober", "goombah", "guffaw", "hocus-pocus", "hogwash", "hoodwink", "hullabaloo", "humbug", "kerfuffle",
    "knucklehead", "lollygag", "malarkey", "mishmash", "monkeyshines", "nincompoop", "noodle", "oogly-boogly", "piddly",
    "poppycock", "rambunctious", "rigmarole", "shenanigans", "skedaddle", "snickerdoodle", "snollygoster", "tiddlywinks",
    "wackadoo", "whatchamacallit", "wiggleworm", "wobblebottom", "wuzzup", "yahoo", "ziggurat", "zonkers", "zoinks"
}


